### ISSUE TITLE
Function Syntax Highlighting works for ES5 not ES6

### ISSUE THREAD

**Issue by 3DEsprit** [decosoftware/deco-ide#127]
Deco 1.1.2/0.7.1 OSX 10.11.5

When declaring functions or methods without the "function" keyword, syntax highlighting is lost for the function. This is also true when calling methods in JSX. Here are some screenshots:

Without highlight using common syntax: http://d.pr/i/17N3G

With highlight using ES5-like syntax: http://d.pr/i/1dNRq

Just to point out before someone says I'm missing "this": Even when applying "this" to the method in the constructor, the method does not highlight in the JSX. 

On a side note, in which part of Deco is this handled? I would be more than happy to send some pull requests in the future for syntax highlighting if possible, especially when this is probably the least of your worries.

**Comment by gdowens** [comment]
Hey @3DEsprit, thanks for checking in.

We are using the "CodeMirror" project for the editor. @dabbott was working on this for some time early this year... you can see we are using his (https://github.com/dabbott/CodeMirror/tree/better-jsx-es6) branch, but that it is incomplete. 

You can see this issue here (https://github.com/codemirror/CodeMirror/issues/3122)  was closed, but then this issue here (https://github.com/codemirror/CodeMirror/issues/3745) was reopened to track the various edge cases that have been missed.

It's an ongoing effort and I'm sure your contributions would be welcome :)

**Comment by 3DEsprit** [comment]
Excellent! I will definitely check out the integration in the near future. :+1:

**Comment by 3DEsprit** [comment]
I'm finally getting caught up with the code-mirror, and CM fork projects. I'll be sure to make some more permanent example screenshots this weekend, as well as integrating my own local branch of the better-jsx fork.

**Comment by dabbott** [comment]
How's this coming?

I'm also happy to pair up on this if you have a branch already.

**Comment by 3DEsprit** [comment]
Just for the sake of documenting the answer, I'll be diving into this more today, and this weekend. No changes have been made yet, but I think I now understand the parser to where I can start testing changes for some of the common issues, specifically the issue with Default, and not being able to use commas in imports when loading individual modules (e.g. React, {Component} ).

**Comment by dabbott** [comment]
I fixed:

`export default class Whatever extends Component`
`export default class extends Component`

In the better-jsx branch. `rm -rf node_modules/codemirror` and `npm i` to pick it up.
